[Settings]
  ID = "c544b2ba-1921-4703-aa92-230aaa4b8632"

[Build]
  Publish = "public"
  Functions = "functions"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    buildDir = "public"